version: '3'
services:
  photo-blog:
    container_name: photo-blog
    build: .
    image: photo-blog:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: photo-blogDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - photo-blog
    depends_on:
      - photo-blogDB
      
  photo-blogDB:
    container_name: photo-blogDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - photo-blog-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - '5432:5432'
    networks:
      - photo-blog
      
  photo-blogAdminer:
    container_name: photo-blogAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=photo-blogDB
    networks:
      - photo-blog
    depends_on:
      - photo-blogDB

  photo-blog-front:
    container_name: photo-blog-front
    build:
      context: ./photo-blog-front
    image: photo-blog-front
    restart: unless-stopped
    ports:
      - '8090:80'
    networks:
      - photo-blog
    depends_on:
      - photo-blog

volumes:
  photo-blog-data:

networks:
  photo-blog:
    name: Photo-blog
    driver: bridge
